// LP Farm Monitor - Real Data from DLMM Simulator
// Reads from data.json (generated by dlmm_simulator.py)

let POSITIONS = [];
let METADATA = {};

async function fetchData() {
    try {
        const res = await fetch('data.json?t=' + Date.now());
        if (!res.ok) throw new Error('Failed to fetch data');
        const data = await res.json();
        POSITIONS = data.positions || [];
        METADATA = data.metadata || {};
        return true;
    } catch (e) {
        console.warn('Using cached data:', e.message);
        return false;
    }
}

function formatUSD(value) {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
}

function getChainClass(chain) {
    return `chain-${chain}`;
}

function getChainLabel(chain) {
    const labels = { solana: "SOL", base: "Base", arbitrum: "ARB" };
    return labels[chain] || chain;
}

function getProtocol(pool_name) {
    return "Meteora DLMM";
}

function getChain(pool_name) {
    return "solana";
}

function isInRange(position) {
    // If IL is very small, position is likely in range
    return Math.abs(position.current_il_pct) < 5;
}

function getRangePercent(position) {
    // Estimate range utilization from IL
    const il = Math.abs(position.current_il_pct);
    if (il < 0.1) return 95;
    if (il < 1) return 80;
    if (il < 3) return 60;
    if (il < 5) return 40;
    return 20;
}

function renderStats(positions) {
    const tvl = positions.reduce((sum, p) => sum + p.capital_usd, 0);
    const fees = positions.reduce((sum, p) => sum + p.accumulated_fee, 0);
    const avgIL = positions.length > 0 ? positions.reduce((sum, p) => sum + p.current_il_pct, 0) / positions.length : 0;
    const totalPnl = positions.reduce((sum, p) => sum + p.current_pnl_usd, 0);
    const avgAPY = positions.length > 0 ? positions.reduce((sum, p) => sum + p.current_apy, 0) / positions.length : 0;
    const inRange = positions.filter(p => isInRange(p)).length;
    const openPositions = positions.filter(p => p.status === 'open');

    document.getElementById('tvl').textContent = formatUSD(tvl);
    document.getElementById('tvl-change').textContent = `${openPositions.length} open positions`;
    document.getElementById('tvl-change').className = 'change positive';

    document.getElementById('fees').textContent = formatUSD(fees);
    const avgHours = positions.length > 0 ? positions.reduce((sum, p) => sum + p.hours_held, 0) / positions.length : 0;
    document.getElementById('fees-change').textContent = `${avgHours.toFixed(1)}h avg hold`;
    document.getElementById('fees-change').className = 'change positive';

    document.getElementById('il').textContent = `${avgIL.toFixed(4)}%`;
    document.getElementById('il').style.color = avgIL < -1 ? 'var(--red)' : 'var(--green)';
    document.getElementById('il-change').textContent = 'avg IL vs HODL';

    document.getElementById('pnl').textContent = formatUSD(totalPnl);
    document.getElementById('pnl').style.color = totalPnl >= 0 ? 'var(--green)' : 'var(--red)';
    document.getElementById('pnl-change').textContent = totalPnl >= 0 ? '↑ Profitable' : '↓ Underwater';
    document.getElementById('pnl-change').className = `change ${totalPnl >= 0 ? 'positive' : 'negative'}`;

    document.getElementById('active-count').textContent = openPositions.length;
    document.getElementById('in-range-count').textContent = `${inRange} in range`;
    document.getElementById('in-range-count').className = `change ${inRange === openPositions.length ? 'positive' : ''}`;

    document.getElementById('apr').textContent = `${avgAPY.toFixed(0)}%`;
    document.getElementById('apr').style.color = 'var(--green)';
    document.getElementById('apr-change').textContent = 'APY (simulated)';

    document.getElementById('position-badge').textContent = `${positions.length} positions`;
}

function renderPositions(positions) {
    const tbody = document.getElementById('positions-body');
    tbody.innerHTML = positions.map(p => {
        const rangePercent = getRangePercent(p);
        const inRange = isInRange(p);
        return `
        <tr>
            <td>
                <strong>${p.pool_name}</strong>
                <div style="font-size:0.7rem;color:var(--muted);margin-top:2px">${getProtocol(p.pool_name)}</div>
                <div style="font-size:0.65rem;color:var(--muted);margin-top:1px">${p.pool_address.slice(0,8)}...</div>
            </td>
            <td><span class="chain-badge chain-solana">SOL</span></td>
            <td>
                ${formatUSD(p.capital_usd)}
                <div style="font-size:0.7rem;color:var(--muted);margin-top:2px">${p.capital_sol.toFixed(4)} SOL</div>
            </td>
            <td class="positive">
                ${formatUSD(p.accumulated_fee)}
            </td>
            <td class="${p.current_il_pct < -1 ? 'negative' : ''}">
                ${p.current_il_pct.toFixed(4)}%
            </td>
            <td class="positive">${p.current_apy.toFixed(0)}%</td>
            <td>
                <div class="range-bar">
                    <div class="fill ${inRange ? 'range-in' : 'range-out'}" style="width:${rangePercent}%"></div>
                </div>
                <span style="font-size:0.7rem;margin-left:6px;color:var(--muted)">${rangePercent}%</span>
            </td>
            <td>
                <span style="color:${inRange ? 'var(--green)' : 'var(--red)'}">
                    ${inRange ? '● In Range' : '○ Out'}
                </span>
                <div style="font-size:0.65rem;color:var(--muted);margin-top:2px">${p.hours_held.toFixed(1)}h</div>
            </td>
        </tr>
    `}).join('');
}

function updateTime() {
    const now = new Date();
    document.getElementById('update-time').textContent = now.toLocaleString();
    if (METADATA.last_update) {
        const lastUpdate = new Date(METADATA.last_update * 1000);
        document.getElementById('last-update').textContent = `Data: ${lastUpdate.toLocaleTimeString()}`;
    } else {
        document.getElementById('last-update').textContent = `Last: ${now.toLocaleTimeString()}`;
    }
}

// Initial load
async function init() {
    await fetchData();
    renderStats(POSITIONS);
    renderPositions(POSITIONS);
    updateTime();
}

init();

// Auto-refresh every 30 seconds
setInterval(async () => {
    await fetchData();
    renderStats(POSITIONS);
    renderPositions(POSITIONS);
    updateTime();
}, 30000);
